apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-certificate-staging
  namespace: cert-manager
spec:
  secretName: acme-certificate-secret-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'YOUR_DOMAIN'
  usages:
    - digital signature
    - key encipherment
    - server auth